/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.64
 * Generated at: 2021-05-03 02:16:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/dev/projects/JaeHoon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1617582441146L));
    _jspx_dependants.put("jar:file:/D:/dev/projects/JaeHoon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<script src='https://code.jquery.com/jquery-3.3.1.min.js'></script>\r\n");
      out.write("\t<title>회원가입</title> \r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>*는 필수 입력\r\n");
      out.write("\t\t<form name=\"frm\" method=\"post\" autocomplete=\"off\" onsubmit=\"return memReg(this);\">\r\n");
      out.write(" \t\t<p>\r\n");
      out.write("\t\t\t<label for=\"user_id\">* 아이디</label>\r\n");
      out.write("  \t\t\t<input type=\"text\" id=\"user_id\" name=\"user_id\" />\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"중복확인\" onclick=\"idCheck()\">\r\n");
      out.write(" \t\t</p>  \r\n");
      out.write(" \t\t<p>\r\n");
      out.write("\t\t\t<label for=\"user_pass\">* 패스워드</label>\r\n");
      out.write("\t\t\t<input type=\"password\" name=\"user_pass\" id=\"user_pass\"/>\r\n");
      out.write(" \t\t</p>\r\n");
      out.write(" \t\t<p>\r\n");
      out.write("\t\t\t<label for=\"user_pass\">* 패스워드 확인</label>\r\n");
      out.write("\t\t\t<input type=\"password\" id=\"user_pass2\"/>\r\n");
      out.write(" \t\t</p>\r\n");
      out.write(" \t\t<p>\r\n");
      out.write("\t\t\t<label>* 닉네임</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"user_name\" name=\"user_name\"/>\r\n");
      out.write(" \t\t</p>\r\n");
      out.write(" \t\t<p>\r\n");
      out.write("\t\t\t<label>* 성별</label>\r\n");
      out.write("\t\t\t<input type=\"radio\" id=\"gender1\" name=\"gender\" value=\"M\">남\r\n");
      out.write("\t\t\t<input type=\"radio\" id=\"gender2\" name=\"gender\" value=\"W\">여\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<label>[선택] 취미</label>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" id=\"hobby1\" name=\"hobby\" value=\"농구\">\r\n");
      out.write("\t\t\t<label for=\"hobby1\">농구</label>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" id=\"hobby2\" name=\"hobby\" value=\"축구\">\r\n");
      out.write("\t\t\t<label for=\"hobby2\">축구</label>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" id=\"hobby3\" name=\"hobby\" value=\"탁구\">\r\n");
      out.write("\t\t\t<label for=\"hobby3\">탁구</label>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" id=\"hobby4\" name=\"hobby\" value=\"야구\">\r\n");
      out.write("\t\t\t<label for=\"hobby4\">야구</label>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" id=\"hobby5\" name=\"hobby\" value=\"볼링\">\r\n");
      out.write("\t\t\t<label for=\"hobby5\">볼링</label>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<label>[선택] 학교</label>\r\n");
      out.write("\t\t\t<select id=\"sc_num\" name=\"sc_num\">\r\n");
      out.write("\t\t\t\t<option selected value = 0>선택</option>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</p>\r\n");
      out.write(" \t\t<p>\r\n");
      out.write("   \t\t\t<button type=\"submit\" id=\"submit\" disabled=\"disabled\">가입</button>  \r\n");
      out.write(" \t\t</p>\r\n");
      out.write(" \t\t</form>\r\n");
      out.write(" \t\t<p>\r\n");
      out.write("\t\t\t<button onclick=\"location.href='/controller/'\">돌아가기</button>\r\n");
      out.write(" \t\t</p>\r\n");
      out.write(" \t</body>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\tfunction memReg(obj) {\r\n");
      out.write("\t\r\n");
      out.write("\t\tif (obj.user_pass.value.length == 0) {\r\n");
      out.write("\t\t\talert(\"패스워드를 입력하세요\");\r\n");
      out.write("\t\t\tobj.user_pass.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t    }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (obj.user_pass2.value.length == 0) {\r\n");
      out.write("\t\t\talert(\"패스워드확인을 입력하세요\");\r\n");
      out.write("\t\t\tobj.user_pass2.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t    }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (obj.user_pass.value != obj.user_pass2.value) {\r\n");
      out.write("\t\t\talert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t\tobj.user_pass2.value = \"\";\r\n");
      out.write("\t\t\tobj.user_pass2.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (obj.user_name.value == '') {\r\n");
      out.write("\t        alert(\"닉네임을 작성해 주세요\");\r\n");
      out.write("\t        obj.user_name.focus();\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t    }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (obj.gender.value == '') {\r\n");
      out.write("\t        alert(\"성별을 선택해 주세요\");\r\n");
      out.write("\t        obj.gender1.focus();\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t    }\t\r\n");
      out.write("\t\tif (confirm(\"회원가입을 하시겠습니까?\")){\r\n");
      out.write("\t\t\talert(\"회원가입이 되었습니다\")\r\n");
      out.write("\t\t\t//$(\"#frm\").submit();\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction idCheck() {\r\n");
      out.write("\t    \r\n");
      out.write("\t    var user_id = $(\"#user_id\").val();\r\n");
      out.write("\t    \r\n");
      out.write("\t    if(user_id.replace(/ /g, \"\") == \"\") { \r\n");
      out.write("\t        alert(\"아이디에는 공백이 들어갈 수 없습니다.\");        \r\n");
      out.write("\t    } else {             \r\n");
      out.write("\t        if(user_id.replace(/ /g, \"\").length > 0) {\r\n");
      out.write("\t            $.ajax({\r\n");
      out.write("\t                type : 'POST', \r\n");
      out.write("\t                data: {\r\n");
      out.write("\t                \t\"user_id\" : user_id\r\n");
      out.write("\t                },\r\n");
      out.write("\t                url: \"/controller/member/idCheck\",\r\n");
      out.write("\t                success: function(count) {\r\n");
      out.write("\t                    if(count > 0) {\r\n");
      out.write("\t                        alert(\"해당 아이디 존재\");    \r\n");
      out.write("\t                        $(\"#submit\").attr(\"disabled\", false);\r\n");
      out.write("\t                        window.location.reload();\r\n");
      out.write("\t                    } else {\r\n");
      out.write("\t                        alert(\"사용가능 아이디\");\r\n");
      out.write("\t                        $(\"#user_id\").attr(\"readonly\",\"readonly\");\r\n");
      out.write("\t                        $(\"#submit\").removeAttr(\"disabled\");\r\n");
      out.write("\t                    }            \r\n");
      out.write("\t                },\r\n");
      out.write("\t                error: function(xhr, status, error) {\r\n");
      out.write("\t                    alert(\"아이디를 입력해주세요..\");\r\n");
      out.write("\t                }        \r\n");
      out.write("\t            });\r\n");
      out.write("\t        } else {\r\n");
      out.write("\t            alert(\"아이디를 입력해주세요...\");\r\n");
      out.write("\t        }        \r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("    </script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/member/register.jsp(51,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/register.jsp(51,4) '${scList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${scList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/member/register.jsp(51,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("info");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.sc_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.sc_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
